import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },

    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "젤리",
      slug: "jelly",
      category: "jelly",
      image: "/images/item1.jpg",
      price: 100,
      brand: "gome jelly",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "곰 젤리 입니다",
    },
    {
      name: "당근 케이크",
      slug: "carrot-cake",
      category: "cake",
      image: "/images/item2.jpg",
      price: 20000,
      brand: "carrot cake",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "당근 케익입니다",
    },
    {
      name: "라즈베리 케이크",
      slug: "raspberry-cake",
      category: "cake",
      image: "/images/item3.jpg",
      price: 23000,
      brand: "Raspberry Cake",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "라즈베리 케익입니다",
    },
    {
      name: "마카롱 세트",
      slug: "macaron-set",
      category: "macaron",
      image: "/images/item4.jpg",
      price: 10000,
      brand: "macaron set",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "마카롱 세트입니다",
    },
    {
      name: "초코 브라우니",
      slug: "chocolate-brownie",
      category: "brownie",
      image: "/images/item5.jpg",
      price: 18000,
      brand: "Chocolate Brownie",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "초코 브라우니입니다",
    },
    {
      name: "비틀즈",
      slug: "beatles",
      category: "jelly",
      image: "/images/item6.jpg",
      price: 700,
      brand: "Beatles",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "비틀즈 입니다",
    },
    {
      name: "크로와상",
      slug: "croissant",
      category: "bread",
      image: "/images/item7.jpg",
      price: 1400,
      brand: "croissant",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "크로와상 입니다",
    },
    {
      name: "트윅스",
      slug: "twix",
      category: "chocolatebar",
      image: "/images/item8.jpg",
      price: 2000,
      brand: "chocolate bar",
      rating: 2.4,
      numReviews: 14,
      countInStock: 10,
      description: "트윅스 입니다",
    },
  ],
};

export default data;
